/**
 * Error codes that are used for api responses
 */
export enum ErrorCodes {
  NOT_MERGED_STATE_TREE = "0",
  NOT_MERGED_MESSAGE_TREE = "1",
  PRIVATE_KEY_MISMATCH = "2",
  POLL_NOT_FOUND = "3",
  DECRYPTION = "4",
  ENCRYPTION = "5",
  FILE_NOT_FOUND = "6",
  SUBGRAPH_DEPLOY = "7",
  SESSION_KEY_NOT_FOUND = "8",
  PIMLICO_API_KEY_NOT_SET = "9",
  INVALID_APPROVAL = "10",
  UNSUPPORTED_NETWORK = "11",
  RPC_API_KEY_NOT_SET = "12",
  FAILED_TO_MERGE_STATE_TREE = "13",
  FAILED_TO_MERGE_MESSAGE_SUBTREES = "14",
  FAILED_TO_MERGE_MESSAGE_TREE = "15",
}
