/**
 * Error codes that are used for api responses
 */
export enum ErrorCodes {
  NOT_MERGED_STATE_TREE,
  PRIVATE_KEY_MISMATCH,
  POLL_NOT_FOUND,
  DECRYPTION,
  ENCRYPTION,
  FILE_NOT_FOUND,
  SUBGRAPH_DEPLOY,
  SESSION_KEY_NOT_FOUND,
  PIMLICO_API_KEY_NOT_SET,
  INVALID_APPROVAL,
  UNSUPPORTED_NETWORK,
  RPC_API_KEY_NOT_SET,
  FAILED_TO_MERGE_STATE_TREE,
  FAILED_TO_MERGE_MESSAGE_SUBTREES,
  FAILED_TO_MERGE_MESSAGE_TREE,
}
