name: Typo Check

on:
  push:
    branches: [dev]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  typos:
    name: Spell Check with Typos
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use typos with config file
        uses: crate-ci/typos@v1.27.3
        with:
          config: .github/workflows/config/typos.toml
